title: Deep Learning And AI Revolution - The 4th Industrial Revolution
email: hmpakula@gmail.com
description: Blogs by hajimupakura | hmpakula@gmail.com
baseurl: ""
url: "https://hajimupakura.github.io"
twitter_username: hajimupakura
github_username:  hmupakura
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-gist
  - execjs
exclude:
  - Gemfile
  - Gemfile.lock
